sudo: false
language: c
compiler:
    - clang
    - gcc
notifications:
    email: false
install:
    - bash install-deps.sh
before_script:
    - export GIT_SVN_TEST_OPTS=--verbose
    - export CPPFLAGS=-I$HOME/workspace/opt/include/subversion-1
    - export LDFLAGS=-L$HOME/workspace/opt/lib
    - export PATH=$HOME/workspace/opt/bin:$PATH
    - export LD_LIBRARY_PATH=$HOME/workspace/opt/lib:$LD_LIBRARY_PATH
script:
    - make && make test
